channels:
  - conda-forge
  - defaults
dependencies:
  # support multiple kernels in multiple conda envs
  - nb_conda_kernels=2.3.1

  # kerberos for HPC authentication
  - krb5=1.17.2

  # used so that instructors can distribute their git files to students in jupyterhub
  - nbgitpuller=1.1.0

  # scipy stack for general scientific computation
  - numpy=1.21.2
  - scipy=1.7.1
  - matplotlib=3.4.3
  - pandas=1.3.2
  - sympy=1.8

  # scale calculations for numpy/pandas/etc.
  - dask=2021.8.0

  # ipympl for matplotlib+jupyter integration
  - ipympl=0.7.0

  # some jupyter widgets
  # - ipyvolume=0.6.0a8
  - nglview=3.0.3
  - ipycytoscape=1.2.2
  - ipygany=0.5.0

  # scikits for machine learning and image processing
  - scikit-learn=0.24.2
  - scikit-image=0.18.2

  # color palettes for matplotlib
  - palettable=3.3.0

  # faster expression evaluator, jit compiler, and array functions for numpy
  - numexpr=2.7.3
  - numba=0.53.1
  - bottleneck=1.3.2

  # extending python and allowing it to interop with C for performance
  - cython=0.29.24

  # python wrapper for ipopt for nonlinear optimization
  - cyipopt=1.0.3

  # specify molecular structures in pandas
  - biopandas=0.2.7

  # molecular descriptor calculator
  - mordred=1.2.0

  # popular python library for astronomy
  - astropy=4.3.1

  # python library for cartography
  - cartopy=0.18.0

  # generic mapping tools
  - pygmt=0.3.1

  # python api for searching in the protein data bank
  - pypdb=2.0

  # spherical harmonics tools
  - pyshtools=4.8

  # package for parsing html
  - beautifulsoup4=4.9.3

  # packages for Max Rudolph's GEL240 class
  - affine=2.3.0
  - rasterio=1.2.1

  # use R from python
  # - rpy2=3.3.2 # NOTE not installing since this requires R version 3.6.x, not the 4.0.x we're installing

  # several common data visualization packages
  - seaborn=0.12.0
  - bokeh=2.4.3
  - bqplot=0.12.36

  # python/threejs binding for jupyter visualization
  - pythreejs=2.3.0

  # interactive leaflet maps in python
  - ipyleaflet=0.17.1

  # interactive webapps in python
  - dash=2.7.1
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0

  # python to vega translator
  - vincent=0.4.4

  # common statistical model libraries
  - statsmodels=0.13.2
  - patsy=0.5.2

  # python data serialization
  - dill=0.3.5.1

  # HDF4 and HDF5 suport, common file formats for numerical data
  # and python packages to support them
  - h5py=3.3.0
  - pytables=3.6.1
  - hdf4=4.2.15

  # read data from excel spreadsheets
  - xlrd=2.0.1

  # interactive learning material for mechanical vibrations
  - resonance=0.22.0

  # toolkit for multi-body dynamics
  - pydy=0.5.0

  # optimizing dynamic systems using direct collocation
  # - opty=1.0.0 # NOTE not installing due to it only having packages for python up to 3.6. repackage?

  # common linear algebra library
  # highest version is 2.17, but it conflicts with xeus-cling
  - blas=2.111

  # octave kernel (octave itself installed through apt, see apt.txt for details
  - octave_kernel=0.32.0

  # R
  # NOTE: the conda build pack will autoinstall irkernel and rstudio
  # however, f**k dependency hell so we're helping it out a bit by installing irkernel and r-devtools here explicitly
  - r-essentials=4.0
  - r-irkernel=1.2
  - r-devtools=2.4.2

  # common package collection
  - r-tidyverse=1.3.2

  # make interactive maps in R
  - r-leaflet=2.1.1

  # univariate time series forecasts
  - r-forecast=8.17.0

  # create dashboards with shiny
  - r-shinydashboard=0.7.2

  # R interface for apache spark
  - r-sparklyr=1.7.8

  # simple features for spacial vector data
  - r-sf=0.9_7

  # nyc flights dataset
  - r-nycflights13=1.0.2

  # sqlite support in r
  - r-rsqlite=2.2.8

  # libcurl in r
  - r-rcurl=1.98_1.3

  # shiny gadget to create ggplot2 charts
  - r-esquisse=1.1.2

  # package manager for the bioconductor project
  - r-biocmanager=1.30.18

  # packages for Lindsay Poirier's class
  - r-rgdal=1.5_16
  - r-maptools=1.1_4

  # c++ kernel
  - xeus-cling=0.12.1

  # sagemath (kernel included)
  - sage=9.2

  # ipyparallel
  - ipyparallel=6.3.0

  # allow installation of pip packages
  - pip=21.0.1

  - pip:

    # visualization for ml datasets
    - facets-overview==1.0.0

    # package requested by Richard
    - diagrams==0.23.1

    # jupyter archive extension
    - jupyter-archive==3.0.1

    # jupyter git extension
    - jupyterlab-git==0.39.2

    # jupyterlab latex extension
    - jupyterlab-latex==3.1.0

    # ngshare for instructors to create courses and grade assignments
    # (auto installs nbgrader)
    - ngshare_exchange==0.5.3
