channels:
  - conda-forge
  - defaults
dependencies:
  # support multiple kernels in multiple conda envs
  - nb_conda_kernels

# pin jupyterlab
  - jupyterlab=3

# scipy stack for general scientific computation
  - numpy
  - scipy
  - matplotlib
  - pandas
  - sympy

# ipympl for matplotlib+jupyter integration
  - ipympl

  # some jupyter widgets
  - ipyvolume
  - nglview
  - ipycytoscape
  - ipygany
  - bokeh
  - bqplot
  - pythreejs
  - ipyleaflet
