channels:
  - conda-forge
  - defaults
dependencies:
  # support multiple kernels in multiple conda envs
  - nb_conda_kernels

  # kerberos for HPC authentication
  - krb5

  # used so that instructors can distribute their git files to students in jupyterhub
  - nbgitpuller

  # nbgrader and ngshare for instructors to create courses and grade assignments
  - nbgrader

  # scipy stack for general scientific computation
  - numpy
  - scipy
  - matplotlib
  - pandas
  - sympy

  # scale calculations for numpy/pandas/etc.
  - dask

  # ipympl for matplotlib+jupyter integration
  - ipympl

  # some jupyter widgets
  #- ipyvolume
  - nglview
  - ipycytoscape
  - ipygany

  # scikits for machine learning and image processing
  - scikit-learn
  - scikit-image

  # color palettes for matplotlib
  - palettable

  # faster expression evaluator, jit compiler, and array functions for numpy
  - numexpr
  - numba
  - bottleneck

  # extending python and allowing it to interop with C for performance
  - cython

  # python wrapper for ipopt for nonlinear optimization
  - cyipopt

  # specify molecular structures in pandas
  - biopandas

  # molecular descriptor calculator
  - mordred

  # popular python library for astronomy
  - astropy

  # python library for cartography
  - cartopy

  # generic mapping tools
  - pygmt

  # python api for searching in the protein data bank
  - pypdb

  # spherical harmonics tools
  - pyshtools

  # package for parsing html
  - beautifulsoup4

  # packages for Max Rudolph's GEL240 class
  - affine
  - rasterio

  # use R from python
  # - rpy2=3.3.2 # NOTE not installing since this requires R version 3.6.x, not the 4.0.x we're installing

  # several common data visualization packages
  - seaborn
  - bokeh
  - bqplot

  # python/threejs binding for jupyter visualization
  - pythreejs

  # interactive leaflet maps in python
  - ipyleaflet

  # interactive webapps in python
  - dash

  # python to vega translator
  - vincent

  # common statistical model libraries
  - statsmodels
  - patsy

  # python data serialization
  - dill

  # HDF4 and HDF5 suport, common file formats for numerical data
  # and python packages to support them
  - h5py
  - pytables
  - hdf4

  # read data from excel spreadsheets
  - xlrd

  # interactive learning material for mechanical vibrations
  - resonance

  # toolkit for multi-body dynamics
  - pydy

  # optimizing dynamic systems using direct collocation
  # - opty=1.0.0 # NOTE not installing due to it only having packages for python up to 3.6. repackage?

  # common linear algebra library
  # highest version is 2.17, but it conflicts with xeus-cling
  - blas

  # octave kernel (octave itself installed through apt, see apt.txt for details
  - octave_kernel

  # R
  # NOTE: the conda build pack will autoinstall irkernel and rstudio
  # however, f**k dependency hell so we're helping it out a bit by installing irkernel and r-devtools here explicitly
  - r-essentials
  - r-irkernel
  - r-devtools

  # common package collection
  - r-tidyverse

  # make interactive maps in R
  - r-leaflet

  # univariate time series forecasts
  - r-forecast

  # create dashboards with shiny
  - r-shinydashboard

  # R interface for apache spark
  - r-sparklyr

  # simple features for spacial vector data
  - r-sf

  # nyc flights dataset
  - r-nycflights13

  # sqlite support in r
  - r-rsqlite

  # libcurl in r
  - r-rcurl

  # shiny gadget to create ggplot2 charts
  - r-esquisse

  # package manager for the bioconductor project
  - r-biocmanager

  # packages for Lindsay Poirier's class
  - r-rgdal
  - r-maptools

  # c++ kernel
  - xeus-cling

  # sagemath (kernel included)
  - sage
 
  # allow installation of pip packages
  - pip

  - pip:

    # visualization for ml datasets
    - facets-overview

    # package requested by Richard
    - diagrams
