name: base
channels:
  - conda-forge
  - defaults
dependencies:

  # support multiple kernels in multiple conda envs
  - nb_conda_kernels=2.2.3

  # scipy stack for general scientific computation
  - numpy=1.19.1
  - scipy=1.5.2
  - matplotlib=3.3.0
  - pandas=1.1.0
  - sympy=1.6.1

  # ipympl for matplotlib+jupyter integration
  - ipympl=0.5.7

  # scikits for machine learning and image processing
  - scikit-learn=0.23.1
  - scikit-image=0.17.1

  # matplotlib animation support
  - ffmpeg=4.3

  # faster expression evaluator and jit compiler for numpy
  - numexpr=2.7.1
  - numba=0.50.1

  # several common data visualization packages
  - seaborn=0.10.1
  - bokeh=2.1.1
  - bqplot=0.12.14

  # common statistical model libraries
  - statsmodels=0.11.1
  - patsy=0.5.1

  # python support for HDF5, a common file format for numerical data
  # also installs hdf5 itself
  - h5py=2.10.0

  # pytables for managing HDF5 data efficiently
  - pytables=3.6.1

  # octave and kernel
  - octave=4.2.1
  - octave_kernel=0.32.0

  # R
  # NOTE: the conda build pack will autoinstall irkernel and rstudio
  - r-essentials=4.0

  # c++ kernel
  - xeus-cling=0.9.0

  # allow installation of pip packages
  - pip=20.0.2
  - pip:
    # visualization for ml datasets
    - facets-overview==1.0.0

